app/authentication/routes.py
from forms import UserSignUpForm, UserSigninForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash


# imports for flask login
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

# from flask_oauth import OAuth

# oauth = OAuth()

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignUpForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = form.password.data
            print(email, first_name, last_name, password)

            user = User(email, first_name, last_name, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'User-created')
            return redirect(url_for('site.home'))
            
            
            
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('signup.html', form=form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserSigninForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                

                login_user(logged_user)


                flash('You were successful in your login. Congratulations, and welcome to the Book Inquiries Page.', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('You do not have access to this content bacause you do not have the proper authorization.', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your Form and Validate Your Information.')
    return render_template('signin.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for
from models import db, User, Book, book_schema, books_schema
from flask_login import current_user


site = Blueprint('site', __name__,template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/books')
def books():
    books = Book.query.all()
    return render_template('books.html', books=books)

@site.route('/update')
def update():
    return render_template('update.html')

@site.route('/create_book', methods=['POST'])
def create_book():

    isbn = request.form['isbn']
    year = request.form['year']
    title = request.form['title']
    pages = request.form['pages']
    author = request.form['author']

    
    user_id = current_user.token
    
    # get user info
    
    book = Book(isbn = isbn, year=year, title=title, pages=pages, author=author, user_id = user_id )
    db.session.add(book)
    db.session.commit()
    
    return redirect(url_for('site.books'))


@site.route('/update_book/<isbn>/edit', methods=['POST', 'PUT'])
def update_book(isbn):
    book = Book.query.filter_by(isbn=isbn).first()

    if request.method in ['POST', 'PUT']:
        print("I printed!")
        if book:
            book.isbn = request.form['isbn']
            book.year = request.form['year']
            book.title = request.form['title']
            book.pages = request.form['pages']
            book.author = request.form['author']
            book.user_id = current_user.id

            db.session.commit()
            return redirect(url_for('site.books'))
        else:
            return "Book does not exist."
    return render_template('update.html', book=book)

@site.route('/delete_book/<isbn>', methods=['POST'])
def delete_book(isbn):
    book = Book.query.get(isbn)
    if book:
        db.session.delete(book)
        db.session.commit()
        return redirect(url_for('site.books'))
    
    
    return redirect(url_for('site.books'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Please enter your description."/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

<title>The Library App</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home') }}" class="navbar-brand">The Library App</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('site.books') }}" class="nav-link">The Library App</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<!--  -->
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "First Name") }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Last Name") }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter Email") }}
        </fieldset>
    </div>
    
    <fieldset id="pass-field">
        {{ form.password.label }}
        {{ form.password(class = "form-control", placeholder = "Enter Password") }}
    </fieldset>
        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>

app/templates/forms_signin.html
<form method="POST">
    
    {{ form.hidden_tag() }}

    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter Email") }}
        </fieldset>
    </div> 
    
    <fieldset id="pass-field">
        {{ form.password.label }}
        {{ form.password(class = "form-control", placeholder = "Enter Password") }}
    </fieldset>
    
        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>